In [1]:
# libraries
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from lorenz import lorenzDatasetWrapper
from plotters import plot_data
from tuning import make_train_GCN, plot_model_results


2023-03-29 15:29:29.145328: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
from spektral.datasets.citation import Citation
from spektral.transforms import LayerPreprocess
from spektral.layers import GCNConv


In [13]:
cora_dataset = Citation("cora", normalize_x=True, transforms=None)


Pre-processing node features


/Users/h.lu/Documents/_code/_research lorenz code/lorenzGNN/lorenzvenv/lib/python3.9/site-packages/scipy/sparse/_index.py:146: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


In [14]:
cora_dataset_preprocess = Citation("cora", normalize_x=True, transforms=[LayerPreprocess(GCNConv)])


Pre-processing node features


In [16]:
print(cora_dataset[0].a.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [15]:
print(cora_dataset_preprocess[0].a.todense())

[[0.25       0.         0.         ... 0.         0.         0.        ]
 [0.         0.25       0.20412415 ... 0.         0.         0.        ]
 [0.         0.20412415 0.16666667 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.49999997 0.         0.        ]
 [0.         0.         0.         ... 0.         0.19999999 0.19999999]
 [0.         0.         0.         ... 0.         0.19999999 0.19999999]]
